version: '2'

services:

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:2e4d8adddc55320796b22a5d2bb2cad43728d2be"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-gatewayrs:e7e9183f3ed1b479f18a61dbabb8430ebd26d0a7"
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'RELEASE_BUMPER=foobar'
    labels:
      io.balena.features.dbus: '1'

  gwmfr:
    image: "nebraltd/hm-gwmfr:9a1e553899ca95edb8d14afee4c105c1950bcc0e"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure

  upnp:
    image: "nebraltd/hm-upnp:4235b4175587fceab5e79c4e4790f1ff8da34bba"
    network_mode: "host"
    restart: on-failure
    volumes:
      - 'pktfwdr:/var/pktfwd'
      
volumes:
  miner-storage:
  miner-log:
  pktfwdr:
